### ISSUE TITLE
Which Version of Node.js Should you use in your .travis.yml file?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-travis#14]
http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
We should update the readme to reflect the fact that a _specific_ node.js version can be selected for test.

> Always use the latest (TLS) version of node.

Tip: if you specify only the **major** number e.g. v4 travis will automatically use the latest stable.

**Comment by Fl4m3Ph03n1x** [comment]
IMHO, placing specific versions of travis is a recipe for deprecation. I usually run with the latest version:

```
language: node_js
node_js:
 - "node"
```

If you really insist in putting a specific version, you are pretty much saying "I will always keep an eye on this tutorial to update it because every X months node releases a new stable version and in X - Y months this tutorial will be deprecated and may not aid new users" (like the TDD tut where people can't use ECMA 6).

With my suggestion, your tutorial would always be up to date. I am not against keeping an eye and maintaining tutorials, I just think that it is humanly impossible to keep every single tutorial dwyl has up to date and that sooner or later someone will stop caring.

**Comment by nelsonic** [comment]
Agreed. will be updating this. 👍

**Comment by rachaelcodes** [comment]
Just as an fyi, a few of us in the current FAC cohort have come unstuck by copying an old node version into their travis.yml - an update would be much clearer. Thanks 😄

**Comment by nelsonic** [comment]
@rachaelcodes pull requests _always_ welcome! 😉
